global using CrossMacro.Application.Automation;
global using CrossMacro.Application.Runtime;
global using CrossMacro.Core.Diagnostics;
global using CrossMacro.Core.Logging;
global using CrossMacro.Core.Models;
global using CrossMacro.Core.Resources;
global using CrossMacro.Core.Services.Playback;
global using CrossMacro.Core.Services.TextExpansion;
global using CrossMacro.Core.Services;
global using CrossMacro.Core;
global using CrossMacro.Infrastructure.Helpers;
global using CrossMacro.Infrastructure.Logging;
global using CrossMacro.Infrastructure.Serialization;
global using CrossMacro.Infrastructure.Services.Playback;
global using CrossMacro.Infrastructure.Services.Recording.Processors;
global using CrossMacro.Infrastructure.Services.ScreenCapture;
global using CrossMacro.Infrastructure.Services.ScreenReading;
global using CrossMacro.Infrastructure.Services.TextExpansion;
global using CrossMacro.Infrastructure.Services;
global using CrossMacro.Platform.Abstractions.Diagnostics;
global using CrossMacro.Platform.Abstractions;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.DependencyInjection;
global using Serilog.Core;
global using Serilog.Events;
global using Serilog;
global using LoggerConfiguration = Serilog.LoggerConfiguration;
global using Log = CrossMacro.Core.Logging.Log;
global using SerilogLog = Serilog.Log;
global using System.Buffers.Binary;
global using System.Buffers;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO.Compression;
global using System.IO;
global using System.Linq;
global using System.Net.Http.Json;
global using System.Net.Http;
global using System.Numerics;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using System.Text.Json.Serialization.Metadata;
global using System.Text.Json.Serialization;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Text;
global using System.Threading.Channels;
global using System.Threading.Tasks;
global using System.Threading;
global using System;
global using TextExpansionModel = CrossMacro.Core.Models.TextExpansionEntry;
global using static CrossMacro.Infrastructure.Services.Playback.WindowCommandHelpers;
