version: 2
updates:
  # Dependabot is disabled by setting the PR limit to zero.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    groups:
      dependencies:
        patterns:
          - "*"
