using CrossMacro.Mcp.Contracts;

namespace CrossMacro.Mcp.Serialization;

[JsonSerializable(typeof(McpToolDefinition))]
[JsonSerializable(typeof(McpToolDefinition[]))]
[JsonSerializable(typeof(McpOperationCapabilityDefinition))]
[JsonSerializable(typeof(McpOperationCapabilityDefinition[]))]
[JsonSerializable(typeof(McpToolError))]
[JsonSerializable(typeof(McpToolError[]))]
[JsonSerializable(typeof(McpToolOutcome))]
[JsonSerializable(typeof(McpStatusResult))]
[JsonSerializable(typeof(McpActiveProfile))]
[JsonSerializable(typeof(McpCapabilityStatus))]
[JsonSerializable(typeof(McpCapabilityStatus[]))]
[JsonSerializable(typeof(McpCapability[]))]
[JsonSerializable(typeof(McpCapabilitySummary))]
[JsonSerializable(typeof(McpHelpResult))]
[JsonSerializable(typeof(McpAvailableTool))]
[JsonSerializable(typeof(McpAvailableTool[]))]
[JsonSerializable(typeof(McpToolCapabilityStatus))]
[JsonSerializable(typeof(McpToolCapabilityStatus[]))]
[JsonSerializable(typeof(McpMacroListResult))]
[JsonSerializable(typeof(McpMacroFile))]
[JsonSerializable(typeof(McpMacroFile[]))]
[JsonSerializable(typeof(McpMacroInspectResult))]
[JsonSerializable(typeof(McpMacroValidateResult))]
[JsonSerializable(typeof(McpMacroInfo))]
[JsonSerializable(typeof(McpMacroSummary))]
[JsonSerializable(typeof(McpMacroEventBreakdown))]
[JsonSerializable(typeof(McpClipboardTextResult))]
[JsonSerializable(typeof(McpClipboardSetTextResult))]
[JsonSerializable(typeof(McpClipboardImageResult))]
[JsonSerializable(typeof(McpClipboardSetImageResult))]
[JsonSerializable(typeof(McpImageClipboardCapability))]
[JsonSerializable(typeof(McpWindowQueryResult))]
[JsonSerializable(typeof(McpWindowControlResult))]
[JsonSerializable(typeof(McpCommandExecuteResult))]
[JsonSerializable(typeof(McpSettingEntry))]
[JsonSerializable(typeof(McpSettingEntry[]))]
[JsonSerializable(typeof(McpSettingsResult))]
[JsonSerializable(typeof(McpProfile))]
[JsonSerializable(typeof(McpProfile[]))]
[JsonSerializable(typeof(McpProfilesResult))]
[JsonSerializable(typeof(McpTextExpansion))]
[JsonSerializable(typeof(McpTextExpansion[]))]
[JsonSerializable(typeof(McpTextExpansionsResult))]
[JsonSerializable(typeof(McpScheduleResult))]
[JsonSerializable(typeof(McpScheduleTask))]
[JsonSerializable(typeof(McpScheduleTaskRun))]
[JsonSerializable(typeof(McpShortcutResult))]
[JsonSerializable(typeof(McpShortcutTask))]
[JsonSerializable(typeof(McpShortcutTaskRun))]
[JsonSerializable(typeof(McpShortcutWindowRule))]
[JsonSerializable(typeof(ShortcutWindowRule))]
[JsonSerializable(typeof(IReadOnlyList<ShortcutWindowRule>))]
[JsonSerializable(typeof(McpTriggerResult))]
[JsonSerializable(typeof(McpTriggerTask))]
[JsonSerializable(typeof(McpRunImageAsset))]
[JsonSerializable(typeof(McpRunImageAsset[]))]
[JsonSerializable(typeof(IReadOnlyList<McpRunImageAsset>))]
[JsonSerializable(typeof(McpSetupResult))]
[JsonSerializable(typeof(McpDaemonResult))]
[JsonSerializable(typeof(McpWindowInfo))]
[JsonSerializable(typeof(McpWindowInfo[]))]
[JsonSerializable(typeof(McpScreenPoint))]
[JsonSerializable(typeof(McpCursorPositionResult))]
[JsonSerializable(typeof(McpScreenRegion))]
[JsonSerializable(typeof(McpScreenReadResult))]
[JsonSerializable(typeof(McpScreenImageSearchResult))]
[JsonSerializable(typeof(McpScreenshotCaptureResult))]
[JsonSerializable(typeof(McpImageReadResult))]
[JsonSerializable(typeof(McpAutomationOperation))]
[JsonSerializable(typeof(McpAutomationOperationStartResult))]
[JsonSerializable(typeof(McpAutomationOperationStopResult))]
[JsonSerializable(typeof(McpAutomationStartResult))]
[JsonSerializable(typeof(McpAutomationGetResult))]
[JsonSerializable(typeof(McpAutomationStopResult))]
[JsonSerializable(typeof(CallToolResult))]
[JsonSerializable(typeof(TextContentBlock))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    GenerationMode = JsonSourceGenerationMode.Metadata)]
/// <summary>
/// Provides trim-safe JSON metadata for the stable CrossMacro MCP contracts.
/// </summary>
public sealed partial class McpJsonContext : JsonSerializerContext;
