#nullable enable
// <auto-generated />
namespace CrossMacro.UI.Localization;

using System.Globalization;
using System.Resources;

public static class Resources
{
    private static ResourceManager? resourceManager;
    private static CultureInfo? resourceCulture;

    public static ResourceManager ResourceManager =>
        resourceManager ??= new ResourceManager("CrossMacro.UI.Localization.Resources", typeof(Resources).Assembly);

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }
}
