//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossMacro.UI.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CrossMacro.UI.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        public static string MainWindow_MinimizeTooltip {
            get {
                return ResourceManager.GetString("MainWindow_MinimizeTooltip", resourceCulture);
            }
        }
        
        public static string MainWindow_CloseTooltip {
            get {
                return ResourceManager.GetString("MainWindow_CloseTooltip", resourceCulture);
            }
        }
        
        public static string MainWindow_DismissTooltip {
            get {
                return ResourceManager.GetString("MainWindow_DismissTooltip", resourceCulture);
            }
        }
        
        public static string MainWindow_GnomeExtensionTitle {
            get {
                return ResourceManager.GetString("MainWindow_GnomeExtensionTitle", resourceCulture);
            }
        }
        
        public static string MainWindow_UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("MainWindow_UpdateAvailableTitle", resourceCulture);
            }
        }
        
        public static string MainWindow_ViewOnGitHub {
            get {
                return ResourceManager.GetString("MainWindow_ViewOnGitHub", resourceCulture);
            }
        }
        
        public static string MainWindow_UpdateAvailableVersion {
            get {
                return ResourceManager.GetString("MainWindow_UpdateAvailableVersion", resourceCulture);
            }
        }
        
        public static string MainWindow_BackendErrorTitle {
            get {
                return ResourceManager.GetString("MainWindow_BackendErrorTitle", resourceCulture);
            }
        }
        
        public static string MainWindow_BackendTroubleshootingFormat {
            get {
                return ResourceManager.GetString("MainWindow_BackendTroubleshootingFormat", resourceCulture);
            }
        }
        
        public static string MainWindow_BackendTroubleshootingLinux {
            get {
                return ResourceManager.GetString("MainWindow_BackendTroubleshootingLinux", resourceCulture);
            }
        }
        
        public static string MainWindow_BackendTroubleshootingWindows {
            get {
                return ResourceManager.GetString("MainWindow_BackendTroubleshootingWindows", resourceCulture);
            }
        }
        
        public static string MainWindow_BackendTroubleshootingMacOS {
            get {
                return ResourceManager.GetString("MainWindow_BackendTroubleshootingMacOS", resourceCulture);
            }
        }
        
        public static string Navigation_Recording {
            get {
                return ResourceManager.GetString("Navigation_Recording", resourceCulture);
            }
        }
        
        public static string Navigation_Playback {
            get {
                return ResourceManager.GetString("Navigation_Playback", resourceCulture);
            }
        }
        
        public static string Navigation_Files {
            get {
                return ResourceManager.GetString("Navigation_Files", resourceCulture);
            }
        }
        
        public static string Navigation_TextExpansion {
            get {
                return ResourceManager.GetString("Navigation_TextExpansion", resourceCulture);
            }
        }
        
        public static string Navigation_Shortcuts {
            get {
                return ResourceManager.GetString("Navigation_Shortcuts", resourceCulture);
            }
        }
        
        public static string Navigation_Schedule {
            get {
                return ResourceManager.GetString("Navigation_Schedule", resourceCulture);
            }
        }
        
        public static string Navigation_Editor {
            get {
                return ResourceManager.GetString("Navigation_Editor", resourceCulture);
            }
        }
        
        public static string Navigation_Settings {
            get {
                return ResourceManager.GetString("Navigation_Settings", resourceCulture);
            }
        }
        
        public static string Settings_GlobalHotkeys {
            get {
                return ResourceManager.GetString("Settings_GlobalHotkeys", resourceCulture);
            }
        }
        
        public static string Settings_ToggleRecording {
            get {
                return ResourceManager.GetString("Settings_ToggleRecording", resourceCulture);
            }
        }
        
        public static string Settings_TogglePlayback {
            get {
                return ResourceManager.GetString("Settings_TogglePlayback", resourceCulture);
            }
        }
        
        public static string Settings_PauseResumePlayback {
            get {
                return ResourceManager.GetString("Settings_PauseResumePlayback", resourceCulture);
            }
        }
        
        public static string Settings_EnableTrayIcon {
            get {
                return ResourceManager.GetString("Settings_EnableTrayIcon", resourceCulture);
            }
        }
        
        public static string Settings_StartMinimized {
            get {
                return ResourceManager.GetString("Settings_StartMinimized", resourceCulture);
            }
        }
        
        public static string Settings_StartMinimizedDescription {
            get {
                return ResourceManager.GetString("Settings_StartMinimizedDescription", resourceCulture);
            }
        }
        
        public static string Settings_EnableTextExpansion {
            get {
                return ResourceManager.GetString("Settings_EnableTextExpansion", resourceCulture);
            }
        }
        
        public static string Settings_CheckForUpdates {
            get {
                return ResourceManager.GetString("Settings_CheckForUpdates", resourceCulture);
            }
        }
        
        public static string Settings_LogLevel {
            get {
                return ResourceManager.GetString("Settings_LogLevel", resourceCulture);
            }
        }
        
        public static string Settings_LogLevelDescription {
            get {
                return ResourceManager.GetString("Settings_LogLevelDescription", resourceCulture);
            }
        }
        
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        public static string Settings_ThemeDescription {
            get {
                return ResourceManager.GetString("Settings_ThemeDescription", resourceCulture);
            }
        }
        
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        public static string Settings_LanguageDescription {
            get {
                return ResourceManager.GetString("Settings_LanguageDescription", resourceCulture);
            }
        }
        
        public static string Settings_SupportTitle {
            get {
                return ResourceManager.GetString("Settings_SupportTitle", resourceCulture);
            }
        }
        
        public static string Settings_SupportDescription {
            get {
                return ResourceManager.GetString("Settings_SupportDescription", resourceCulture);
            }
        }
        
        public static string Settings_StarOnGitHub {
            get {
                return ResourceManager.GetString("Settings_StarOnGitHub", resourceCulture);
            }
        }
        
        public static string Settings_HotkeyAlreadyAssignedTitle {
            get {
                return ResourceManager.GetString("Settings_HotkeyAlreadyAssignedTitle", resourceCulture);
            }
        }
        
        public static string Language_Auto {
            get {
                return ResourceManager.GetString("Language_Auto", resourceCulture);
            }
        }
        
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        public static string Language_Turkish {
            get {
                return ResourceManager.GetString("Language_Turkish", resourceCulture);
            }
        }
        
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        public static string Status_RecordedEvents {
            get {
                return ResourceManager.GetString("Status_RecordedEvents", resourceCulture);
            }
        }
        
        public static string Status_LoadedMacro {
            get {
                return ResourceManager.GetString("Status_LoadedMacro", resourceCulture);
            }
        }
        
        public static string Status_CreatedMacro {
            get {
                return ResourceManager.GetString("Status_CreatedMacro", resourceCulture);
            }
        }
        
        public static string Recording_LabelStatus {
            get {
                return ResourceManager.GetString("Recording_LabelStatus", resourceCulture);
            }
        }
        
        public static string Recording_LabelEvents {
            get {
                return ResourceManager.GetString("Recording_LabelEvents", resourceCulture);
            }
        }
        
        public static string Recording_LabelState {
            get {
                return ResourceManager.GetString("Recording_LabelState", resourceCulture);
            }
        }
        
        public static string Recording_TooltipRecording {
            get {
                return ResourceManager.GetString("Recording_TooltipRecording", resourceCulture);
            }
        }
        
        public static string Recording_TooltipReady {
            get {
                return ResourceManager.GetString("Recording_TooltipReady", resourceCulture);
            }
        }
        
        public static string Recording_CaptureSettings {
            get {
                return ResourceManager.GetString("Recording_CaptureSettings", resourceCulture);
            }
        }
        
        public static string Recording_Mouse {
            get {
                return ResourceManager.GetString("Recording_Mouse", resourceCulture);
            }
        }
        
        public static string Recording_Keyboard {
            get {
                return ResourceManager.GetString("Recording_Keyboard", resourceCulture);
            }
        }
        
        public static string Recording_Gamepad {
            get {
                return ResourceManager.GetString("Recording_Gamepad", resourceCulture);
            }
        }
        
        public static string Recording_ForceRelativeCoordinates {
            get {
                return ResourceManager.GetString("Recording_ForceRelativeCoordinates", resourceCulture);
            }
        }
        
        public static string Recording_ForceRelativeCoordinatesDescription {
            get {
                return ResourceManager.GetString("Recording_ForceRelativeCoordinatesDescription", resourceCulture);
            }
        }
        
        public static string Recording_ForceRelativeCoordinatesHelp {
            get {
                return ResourceManager.GetString("Recording_ForceRelativeCoordinatesHelp", resourceCulture);
            }
        }
        
        public static string Recording_SkipInitialZeroZero {
            get {
                return ResourceManager.GetString("Recording_SkipInitialZeroZero", resourceCulture);
            }
        }
        
        public static string Recording_SkipInitialZeroZeroDescription {
            get {
                return ResourceManager.GetString("Recording_SkipInitialZeroZeroDescription", resourceCulture);
            }
        }
        
        public static string Recording_StartRecording {
            get {
                return ResourceManager.GetString("Recording_StartRecording", resourceCulture);
            }
        }
        
        public static string Recording_StopRecording {
            get {
                return ResourceManager.GetString("Recording_StopRecording", resourceCulture);
            }
        }
        
        public static string Recording_Tip {
            get {
                return ResourceManager.GetString("Recording_Tip", resourceCulture);
            }
        }
        
        public static string Schedule_ItemsText {
            get {
                return ResourceManager.GetString("Schedule_ItemsText", resourceCulture);
            }
        }
        
        public static string Schedule_DefaultTaskName {
            get {
                return ResourceManager.GetString("Schedule_DefaultTaskName", resourceCulture);
            }
        }
        
        public static string Shortcut_ItemsText {
            get {
                return ResourceManager.GetString("Shortcut_ItemsText", resourceCulture);
            }
        }
        
        public static string Shortcut_DefaultTaskName {
            get {
                return ResourceManager.GetString("Shortcut_DefaultTaskName", resourceCulture);
            }
        }
        
        public static string Schedule_NoFile {
            get {
                return ResourceManager.GetString("Schedule_NoFile", resourceCulture);
            }
        }
        
        public static string Schedule_ListSummary {
            get {
                return ResourceManager.GetString("Schedule_ListSummary", resourceCulture);
            }
        }
        
        public static string Schedule_StatusPlaceholder {
            get {
                return ResourceManager.GetString("Schedule_StatusPlaceholder", resourceCulture);
            }
        }
        
        public static string Shortcut_StatusPlaceholder {
            get {
                return ResourceManager.GetString("Shortcut_StatusPlaceholder", resourceCulture);
            }
        }
        
        public static string Playback_PlaybackSpeed {
            get {
                return ResourceManager.GetString("Playback_PlaybackSpeed", resourceCulture);
            }
        }
        
        public static string Playback_LoopPlayback {
            get {
                return ResourceManager.GetString("Playback_LoopPlayback", resourceCulture);
            }
        }
        
        public static string Playback_RandomizeLoopDelay {
            get {
                return ResourceManager.GetString("Playback_RandomizeLoopDelay", resourceCulture);
            }
        }
        
        public static string Playback_LoopCount {
            get {
                return ResourceManager.GetString("Playback_LoopCount", resourceCulture);
            }
        }
        
        public static string Playback_LoopDelayMs {
            get {
                return ResourceManager.GetString("Playback_LoopDelayMs", resourceCulture);
            }
        }
        
        public static string Playback_LoopDelayRangeMs {
            get {
                return ResourceManager.GetString("Playback_LoopDelayRangeMs", resourceCulture);
            }
        }
        
        public static string Playback_CountdownSec {
            get {
                return ResourceManager.GetString("Playback_CountdownSec", resourceCulture);
            }
        }
        
        public static string Playback_PlayMacro {
            get {
                return ResourceManager.GetString("Playback_PlayMacro", resourceCulture);
            }
        }
        
        public static string Playback_StopPlayback {
            get {
                return ResourceManager.GetString("Playback_StopPlayback", resourceCulture);
            }
        }
        
        public static string Playback_LoopTip {
            get {
                return ResourceManager.GetString("Playback_LoopTip", resourceCulture);
            }
        }
        
        public static string Playback_AbsoluteCoordinatesUnsupportedTitle {
            get {
                return ResourceManager.GetString("Playback_AbsoluteCoordinatesUnsupportedTitle", resourceCulture);
            }
        }
        
        public static string Playback_AbsoluteCoordinatesUnsupportedMessage {
            get {
                return ResourceManager.GetString("Playback_AbsoluteCoordinatesUnsupportedMessage", resourceCulture);
            }
        }
        
        public static string Playback_StatusAbsoluteCoordinatesUnsupported {
            get {
                return ResourceManager.GetString("Playback_StatusAbsoluteCoordinatesUnsupported", resourceCulture);
            }
        }
        
        public static string Playback_PermissionRequiredTitle {
            get {
                return ResourceManager.GetString("Playback_PermissionRequiredTitle", resourceCulture);
            }
        }
        
        public static string Playback_PermissionRequiredMessage {
            get {
                return ResourceManager.GetString("Playback_PermissionRequiredMessage", resourceCulture);
            }
        }
        
        public static string Playback_StatusPermissionRequired {
            get {
                return ResourceManager.GetString("Playback_StatusPermissionRequired", resourceCulture);
            }
        }
        
        public static string Files_LoadedMacros {
            get {
                return ResourceManager.GetString("Files_LoadedMacros", resourceCulture);
            }
        }
        
        public static string Files_RemoveLoadedMacroTooltip {
            get {
                return ResourceManager.GetString("Files_RemoveLoadedMacroTooltip", resourceCulture);
            }
        }
        
        public static string Files_LoadMacro {
            get {
                return ResourceManager.GetString("Files_LoadMacro", resourceCulture);
            }
        }
        
        public static string Files_SaveMacro {
            get {
                return ResourceManager.GetString("Files_SaveMacro", resourceCulture);
            }
        }
        
        public static string Files_SelectedMacro {
            get {
                return ResourceManager.GetString("Files_SelectedMacro", resourceCulture);
            }
        }
        
        public static string Files_MacroName {
            get {
                return ResourceManager.GetString("Files_MacroName", resourceCulture);
            }
        }
        
        public static string Files_MacroNamePlaceholder {
            get {
                return ResourceManager.GetString("Files_MacroNamePlaceholder", resourceCulture);
            }
        }
        
        public static string Files_SequenceRepeat {
            get {
                return ResourceManager.GetString("Files_SequenceRepeat", resourceCulture);
            }
        }
        
        public static string Files_SequenceRepeatDescription {
            get {
                return ResourceManager.GetString("Files_SequenceRepeatDescription", resourceCulture);
            }
        }
        
        public static string Files_PlaybackMode {
            get {
                return ResourceManager.GetString("Files_PlaybackMode", resourceCulture);
            }
        }
        
        public static string Files_PlaybackModeSelectedOnly {
            get {
                return ResourceManager.GetString("Files_PlaybackModeSelectedOnly", resourceCulture);
            }
        }
        
        public static string Files_PlaybackModeSelectedOnlyDescription {
            get {
                return ResourceManager.GetString("Files_PlaybackModeSelectedOnlyDescription", resourceCulture);
            }
        }
        
        public static string Files_PlaybackModeAdvanceSelection {
            get {
                return ResourceManager.GetString("Files_PlaybackModeAdvanceSelection", resourceCulture);
            }
        }
        
        public static string Files_PlaybackModeAdvanceSelectionDescription {
            get {
                return ResourceManager.GetString("Files_PlaybackModeAdvanceSelectionDescription", resourceCulture);
            }
        }
        
        public static string Files_PlaybackModeSequentialCycle {
            get {
                return ResourceManager.GetString("Files_PlaybackModeSequentialCycle", resourceCulture);
            }
        }
        
        public static string Files_PlaybackModeSequentialCycleDescription {
            get {
                return ResourceManager.GetString("Files_PlaybackModeSequentialCycleDescription", resourceCulture);
            }
        }
        
        public static string TextExpansion_AddNewExpansion {
            get {
                return ResourceManager.GetString("TextExpansion_AddNewExpansion", resourceCulture);
            }
        }
        
        public static string TextExpansion_Trigger {
            get {
                return ResourceManager.GetString("TextExpansion_Trigger", resourceCulture);
            }
        }
        
        public static string TextExpansion_TriggerPlaceholder {
            get {
                return ResourceManager.GetString("TextExpansion_TriggerPlaceholder", resourceCulture);
            }
        }
        
        public static string TextExpansion_Replacement {
            get {
                return ResourceManager.GetString("TextExpansion_Replacement", resourceCulture);
            }
        }
        
        public static string TextExpansion_ReplacementPlaceholder {
            get {
                return ResourceManager.GetString("TextExpansion_ReplacementPlaceholder", resourceCulture);
            }
        }
        
        public static string Files_UnnamedMacro {
            get {
                return ResourceManager.GetString("Files_UnnamedMacro", resourceCulture);
            }
        }
        
        public static string Files_SourceSession {
            get {
                return ResourceManager.GetString("Files_SourceSession", resourceCulture);
            }
        }
        
        public static string Files_SequenceRepeatSummary {
            get {
                return ResourceManager.GetString("Files_SequenceRepeatSummary", resourceCulture);
            }
        }
        
        public static string Files_LoadedMacroDescription {
            get {
                return ResourceManager.GetString("Files_LoadedMacroDescription", resourceCulture);
            }
        }
        
        public static string TextExpansion_InsertionMode {
            get {
                return ResourceManager.GetString("TextExpansion_InsertionMode", resourceCulture);
            }
        }
        
        public static string TextExpansion_PasteMethod {
            get {
                return ResourceManager.GetString("TextExpansion_PasteMethod", resourceCulture);
            }
        }
        
        public static string TextExpansion_Add {
            get {
                return ResourceManager.GetString("TextExpansion_Add", resourceCulture);
            }
        }
        
        public static string TextExpansion_SavedExpansions {
            get {
                return ResourceManager.GetString("TextExpansion_SavedExpansions", resourceCulture);
            }
        }
        
        public static string TextExpansion_Items {
            get {
                return ResourceManager.GetString("TextExpansion_Items", resourceCulture);
            }
        }
        
        public static string TextExpansion_NoSavedExpansions {
            get {
                return ResourceManager.GetString("TextExpansion_NoSavedExpansions", resourceCulture);
            }
        }
        
        public static string TextExpansion_EnableInSettingsTip {
            get {
                return ResourceManager.GetString("TextExpansion_EnableInSettingsTip", resourceCulture);
            }
        }
        
        public static string TextExpansion_DeleteTitle {
            get {
                return ResourceManager.GetString("TextExpansion_DeleteTitle", resourceCulture);
            }
        }
        
        public static string TextExpansion_DeleteMessage {
            get {
                return ResourceManager.GetString("TextExpansion_DeleteMessage", resourceCulture);
            }
        }
        
        public static string Schedule_Title {
            get {
                return ResourceManager.GetString("Schedule_Title", resourceCulture);
            }
        }
        
        public static string Schedule_Items {
            get {
                return ResourceManager.GetString("Schedule_Items", resourceCulture);
            }
        }
        
        public static string Schedule_EditTask {
            get {
                return ResourceManager.GetString("Schedule_EditTask", resourceCulture);
            }
        }
        
        public static string Schedule_DeleteTask {
            get {
                return ResourceManager.GetString("Schedule_DeleteTask", resourceCulture);
            }
        }
        
        public static string Schedule_TaskSettings {
            get {
                return ResourceManager.GetString("Schedule_TaskSettings", resourceCulture);
            }
        }
        
        public static string Schedule_Name {
            get {
                return ResourceManager.GetString("Schedule_Name", resourceCulture);
            }
        }
        
        public static string Schedule_NamePlaceholder {
            get {
                return ResourceManager.GetString("Schedule_NamePlaceholder", resourceCulture);
            }
        }
        
        public static string Schedule_PlaybackSpeed {
            get {
                return ResourceManager.GetString("Schedule_PlaybackSpeed", resourceCulture);
            }
        }
        
        public static string Schedule_MacroFile {
            get {
                return ResourceManager.GetString("Schedule_MacroFile", resourceCulture);
            }
        }
        
        public static string Schedule_NoFileSelected {
            get {
                return ResourceManager.GetString("Schedule_NoFileSelected", resourceCulture);
            }
        }
        
        public static string Schedule_Browse {
            get {
                return ResourceManager.GetString("Schedule_Browse", resourceCulture);
            }
        }
        
        public static string Schedule_Type {
            get {
                return ResourceManager.GetString("Schedule_Type", resourceCulture);
            }
        }
        
        public static string Schedule_TypeInterval {
            get {
                return ResourceManager.GetString("Schedule_TypeInterval", resourceCulture);
            }
        }
        
        public static string Schedule_TypeDateTime {
            get {
                return ResourceManager.GetString("Schedule_TypeDateTime", resourceCulture);
            }
        }
        
        public static string Schedule_TypeWeekly {
            get {
                return ResourceManager.GetString("Schedule_TypeWeekly", resourceCulture);
            }
        }
        
        public static string Schedule_RandomizeInterval {
            get {
                return ResourceManager.GetString("Schedule_RandomizeInterval", resourceCulture);
            }
        }
        
        public static string Schedule_RunEveryRange {
            get {
                return ResourceManager.GetString("Schedule_RunEveryRange", resourceCulture);
            }
        }
        
        public static string Schedule_RangeTo {
            get {
                return ResourceManager.GetString("Schedule_RangeTo", resourceCulture);
            }
        }
        
        public static string Schedule_IntervalSettings {
            get {
                return ResourceManager.GetString("Schedule_IntervalSettings", resourceCulture);
            }
        }
        
        public static string Schedule_RunEvery {
            get {
                return ResourceManager.GetString("Schedule_RunEvery", resourceCulture);
            }
        }
        
        public static string Schedule_Seconds {
            get {
                return ResourceManager.GetString("Schedule_Seconds", resourceCulture);
            }
        }
        
        public static string Schedule_Minutes {
            get {
                return ResourceManager.GetString("Schedule_Minutes", resourceCulture);
            }
        }
        
        public static string Schedule_Hours {
            get {
                return ResourceManager.GetString("Schedule_Hours", resourceCulture);
            }
        }
        
        public static string Schedule_DateTimeSettings {
            get {
                return ResourceManager.GetString("Schedule_DateTimeSettings", resourceCulture);
            }
        }
        
        public static string Schedule_RunAt {
            get {
                return ResourceManager.GetString("Schedule_RunAt", resourceCulture);
            }
        }
        
        public static string Schedule_RunOnceTip {
            get {
                return ResourceManager.GetString("Schedule_RunOnceTip", resourceCulture);
            }
        }
        
        public static string Schedule_WeeklySettings {
            get {
                return ResourceManager.GetString("Schedule_WeeklySettings", resourceCulture);
            }
        }
        
        public static string Schedule_RunOn {
            get {
                return ResourceManager.GetString("Schedule_RunOn", resourceCulture);
            }
        }
        
        public static string Schedule_WeeklyEveryDay {
            get {
                return ResourceManager.GetString("Schedule_WeeklyEveryDay", resourceCulture);
            }
        }
        
        public static string Schedule_WeeklyWeekdays {
            get {
                return ResourceManager.GetString("Schedule_WeeklyWeekdays", resourceCulture);
            }
        }
        
        public static string Schedule_WeeklyWeekends {
            get {
                return ResourceManager.GetString("Schedule_WeeklyWeekends", resourceCulture);
            }
        }
        
        public static string Schedule_WeeklyCustom {
            get {
                return ResourceManager.GetString("Schedule_WeeklyCustom", resourceCulture);
            }
        }
        
        public static string Schedule_WeeklyCustomDays {
            get {
                return ResourceManager.GetString("Schedule_WeeklyCustomDays", resourceCulture);
            }
        }
        
        public static string Schedule_Monday {
            get {
                return ResourceManager.GetString("Schedule_Monday", resourceCulture);
            }
        }
        
        public static string Schedule_Tuesday {
            get {
                return ResourceManager.GetString("Schedule_Tuesday", resourceCulture);
            }
        }
        
        public static string Schedule_Wednesday {
            get {
                return ResourceManager.GetString("Schedule_Wednesday", resourceCulture);
            }
        }
        
        public static string Schedule_Thursday {
            get {
                return ResourceManager.GetString("Schedule_Thursday", resourceCulture);
            }
        }
        
        public static string Schedule_Friday {
            get {
                return ResourceManager.GetString("Schedule_Friday", resourceCulture);
            }
        }
        
        public static string Schedule_Saturday {
            get {
                return ResourceManager.GetString("Schedule_Saturday", resourceCulture);
            }
        }
        
        public static string Schedule_Sunday {
            get {
                return ResourceManager.GetString("Schedule_Sunday", resourceCulture);
            }
        }
        
        public static string Schedule_WeeklyTip {
            get {
                return ResourceManager.GetString("Schedule_WeeklyTip", resourceCulture);
            }
        }
        
        public static string Schedule_Status {
            get {
                return ResourceManager.GetString("Schedule_Status", resourceCulture);
            }
        }
        
        public static string Schedule_LastRun {
            get {
                return ResourceManager.GetString("Schedule_LastRun", resourceCulture);
            }
        }
        
        public static string Schedule_NextRun {
            get {
                return ResourceManager.GetString("Schedule_NextRun", resourceCulture);
            }
        }
        
        public static string Schedule_StatusLabel {
            get {
                return ResourceManager.GetString("Schedule_StatusLabel", resourceCulture);
            }
        }
        
        public static string Schedule_Never {
            get {
                return ResourceManager.GetString("Schedule_Never", resourceCulture);
            }
        }
        
        public static string Schedule_NotScheduled {
            get {
                return ResourceManager.GetString("Schedule_NotScheduled", resourceCulture);
            }
        }
        
        public static string Schedule_SaveAllTasks {
            get {
                return ResourceManager.GetString("Schedule_SaveAllTasks", resourceCulture);
            }
        }
        
        public static string Schedule_NoTaskSelected {
            get {
                return ResourceManager.GetString("Schedule_NoTaskSelected", resourceCulture);
            }
        }
        
        public static string Schedule_SelectTaskHint {
            get {
                return ResourceManager.GetString("Schedule_SelectTaskHint", resourceCulture);
            }
        }
        
        public static string Schedule_DeleteTitle {
            get {
                return ResourceManager.GetString("Schedule_DeleteTitle", resourceCulture);
            }
        }
        
        public static string Schedule_DeleteMessage {
            get {
                return ResourceManager.GetString("Schedule_DeleteMessage", resourceCulture);
            }
        }
        
        public static string Schedule_OpenMacroDialogTitle {
            get {
                return ResourceManager.GetString("Schedule_OpenMacroDialogTitle", resourceCulture);
            }
        }
        
        public static string Schedule_OpenMacroDialogFilter {
            get {
                return ResourceManager.GetString("Schedule_OpenMacroDialogFilter", resourceCulture);
            }
        }
        
        public static string Schedule_StatusInitFailed {
            get {
                return ResourceManager.GetString("Schedule_StatusInitFailed", resourceCulture);
            }
        }
        
        public static string Schedule_StatusChangesSaved {
            get {
                return ResourceManager.GetString("Schedule_StatusChangesSaved", resourceCulture);
            }
        }
        
        public static string Schedule_StatusSaveFailed {
            get {
                return ResourceManager.GetString("Schedule_StatusSaveFailed", resourceCulture);
            }
        }
        
        public static string Schedule_SaveFailedTitle {
            get {
                return ResourceManager.GetString("Schedule_SaveFailedTitle", resourceCulture);
            }
        }
        
        public static string Schedule_StatusExtensionWarning {
            get {
                return ResourceManager.GetString("Schedule_StatusExtensionWarning", resourceCulture);
            }
        }
        
        public static string Schedule_StatusRunning {
            get {
                return ResourceManager.GetString("Schedule_StatusRunning", resourceCulture);
            }
        }
        
        public static string Schedule_StatusCompleted {
            get {
                return ResourceManager.GetString("Schedule_StatusCompleted", resourceCulture);
            }
        }
        
        public static string Schedule_StatusFailedExecution {
            get {
                return ResourceManager.GetString("Schedule_StatusFailedExecution", resourceCulture);
            }
        }
        
        public static string Shortcut_Title {
            get {
                return ResourceManager.GetString("Shortcut_Title", resourceCulture);
            }
        }
        
        public static string Shortcut_Items {
            get {
                return ResourceManager.GetString("Shortcut_Items", resourceCulture);
            }
        }
        
        public static string Shortcut_NameFallback {
            get {
                return ResourceManager.GetString("Shortcut_NameFallback", resourceCulture);
            }
        }
        
        public static string Shortcut_NoFile {
            get {
                return ResourceManager.GetString("Shortcut_NoFile", resourceCulture);
            }
        }
        
        public static string Shortcut_EditTooltip {
            get {
                return ResourceManager.GetString("Shortcut_EditTooltip", resourceCulture);
            }
        }
        
        public static string Shortcut_DeleteTooltip {
            get {
                return ResourceManager.GetString("Shortcut_DeleteTooltip", resourceCulture);
            }
        }
        
        public static string Shortcut_Settings {
            get {
                return ResourceManager.GetString("Shortcut_Settings", resourceCulture);
            }
        }
        
        public static string Shortcut_Name {
            get {
                return ResourceManager.GetString("Shortcut_Name", resourceCulture);
            }
        }
        
        public static string Shortcut_NamePlaceholder {
            get {
                return ResourceManager.GetString("Shortcut_NamePlaceholder", resourceCulture);
            }
        }
        
        public static string Shortcut_Trigger {
            get {
                return ResourceManager.GetString("Shortcut_Trigger", resourceCulture);
            }
        }
        
        public static string Shortcut_PlaybackSpeed {
            get {
                return ResourceManager.GetString("Shortcut_PlaybackSpeed", resourceCulture);
            }
        }
        
        public static string Shortcut_LoopPlayback {
            get {
                return ResourceManager.GetString("Shortcut_LoopPlayback", resourceCulture);
            }
        }
        
        public static string Shortcut_PressToStartStop {
            get {
                return ResourceManager.GetString("Shortcut_PressToStartStop", resourceCulture);
            }
        }
        
        public static string Shortcut_PressToStartStopTooltip {
            get {
                return ResourceManager.GetString("Shortcut_PressToStartStopTooltip", resourceCulture);
            }
        }
        
        public static string Shortcut_RunWhenHeld {
            get {
                return ResourceManager.GetString("Shortcut_RunWhenHeld", resourceCulture);
            }
        }
        
        public static string Shortcut_RunWhenHeldTooltip {
            get {
                return ResourceManager.GetString("Shortcut_RunWhenHeldTooltip", resourceCulture);
            }
        }
        
        public static string Shortcut_LoopCount {
            get {
                return ResourceManager.GetString("Shortcut_LoopCount", resourceCulture);
            }
        }
        
        public static string Shortcut_LoopDelayMs {
            get {
                return ResourceManager.GetString("Shortcut_LoopDelayMs", resourceCulture);
            }
        }
        
        public static string Shortcut_LoopTip {
            get {
                return ResourceManager.GetString("Shortcut_LoopTip", resourceCulture);
            }
        }
        
        public static string Shortcut_MacroFile {
            get {
                return ResourceManager.GetString("Shortcut_MacroFile", resourceCulture);
            }
        }
        
        public static string Shortcut_NoFileSelected {
            get {
                return ResourceManager.GetString("Shortcut_NoFileSelected", resourceCulture);
            }
        }
        
        public static string Shortcut_Browse {
            get {
                return ResourceManager.GetString("Shortcut_Browse", resourceCulture);
            }
        }
        
        public static string Shortcut_Status {
            get {
                return ResourceManager.GetString("Shortcut_Status", resourceCulture);
            }
        }
        
        public static string Shortcut_LastTriggered {
            get {
                return ResourceManager.GetString("Shortcut_LastTriggered", resourceCulture);
            }
        }
        
        public static string Shortcut_StatusLabel {
            get {
                return ResourceManager.GetString("Shortcut_StatusLabel", resourceCulture);
            }
        }
        
        public static string Shortcut_Never {
            get {
                return ResourceManager.GetString("Shortcut_Never", resourceCulture);
            }
        }
        
        public static string Shortcut_SaveAll {
            get {
                return ResourceManager.GetString("Shortcut_SaveAll", resourceCulture);
            }
        }
        
        public static string Shortcut_NoSelected {
            get {
                return ResourceManager.GetString("Shortcut_NoSelected", resourceCulture);
            }
        }
        
        public static string Shortcut_SelectHint {
            get {
                return ResourceManager.GetString("Shortcut_SelectHint", resourceCulture);
            }
        }
        
        public static string Shortcut_DeleteTitle {
            get {
                return ResourceManager.GetString("Shortcut_DeleteTitle", resourceCulture);
            }
        }
        
        public static string Shortcut_DeleteMessage {
            get {
                return ResourceManager.GetString("Shortcut_DeleteMessage", resourceCulture);
            }
        }
        
        public static string Shortcut_OpenMacroDialogTitle {
            get {
                return ResourceManager.GetString("Shortcut_OpenMacroDialogTitle", resourceCulture);
            }
        }
        
        public static string Shortcut_OpenMacroDialogFilter {
            get {
                return ResourceManager.GetString("Shortcut_OpenMacroDialogFilter", resourceCulture);
            }
        }
        
        public static string Shortcut_StatusInitFailed {
            get {
                return ResourceManager.GetString("Shortcut_StatusInitFailed", resourceCulture);
            }
        }
        
        public static string Shortcut_StatusChangesSaved {
            get {
                return ResourceManager.GetString("Shortcut_StatusChangesSaved", resourceCulture);
            }
        }
        
        public static string Shortcut_StatusSaveFailed {
            get {
                return ResourceManager.GetString("Shortcut_StatusSaveFailed", resourceCulture);
            }
        }
        
        public static string Shortcut_SaveFailedTitle {
            get {
                return ResourceManager.GetString("Shortcut_SaveFailedTitle", resourceCulture);
            }
        }
        
        public static string Shortcut_StatusRunning {
            get {
                return ResourceManager.GetString("Shortcut_StatusRunning", resourceCulture);
            }
        }
        
        public static string Shortcut_StatusCompleted {
            get {
                return ResourceManager.GetString("Shortcut_StatusCompleted", resourceCulture);
            }
        }
        
        public static string Shortcut_StatusFailed {
            get {
                return ResourceManager.GetString("Shortcut_StatusFailed", resourceCulture);
            }
        }
        
        public static string Files_StatusReady {
            get {
                return ResourceManager.GetString("Files_StatusReady", resourceCulture);
            }
        }
        
        public static string Files_OpenMacroDialogFilter {
            get {
                return ResourceManager.GetString("Files_OpenMacroDialogFilter", resourceCulture);
            }
        }
        
        public static string Files_SaveDialogTitle {
            get {
                return ResourceManager.GetString("Files_SaveDialogTitle", resourceCulture);
            }
        }
        
        public static string Files_LoadDialogTitle {
            get {
                return ResourceManager.GetString("Files_LoadDialogTitle", resourceCulture);
            }
        }
        
        public static string Files_StatusSaveCancelled {
            get {
                return ResourceManager.GetString("Files_StatusSaveCancelled", resourceCulture);
            }
        }
        
        public static string Files_StatusSavedTo {
            get {
                return ResourceManager.GetString("Files_StatusSavedTo", resourceCulture);
            }
        }
        
        public static string Files_StatusSaveError {
            get {
                return ResourceManager.GetString("Files_StatusSaveError", resourceCulture);
            }
        }
        
        public static string Files_StatusLoadCancelled {
            get {
                return ResourceManager.GetString("Files_StatusLoadCancelled", resourceCulture);
            }
        }
        
        public static string Files_StatusLoadUnreadable {
            get {
                return ResourceManager.GetString("Files_StatusLoadUnreadable", resourceCulture);
            }
        }
        
        public static string Files_StatusLoaded {
            get {
                return ResourceManager.GetString("Files_StatusLoaded", resourceCulture);
            }
        }
        
        public static string Files_StatusLoadError {
            get {
                return ResourceManager.GetString("Files_StatusLoadError", resourceCulture);
            }
        }
        
        public static string Files_DeleteLoadedMacroTitle {
            get {
                return ResourceManager.GetString("Files_DeleteLoadedMacroTitle", resourceCulture);
            }
        }
        
        public static string Files_DeleteLoadedMacroMessage {
            get {
                return ResourceManager.GetString("Files_DeleteLoadedMacroMessage", resourceCulture);
            }
        }
        
        public static string Files_StatusRemoved {
            get {
                return ResourceManager.GetString("Files_StatusRemoved", resourceCulture);
            }
        }
        
        public static string Playback_StatusReady {
            get {
                return ResourceManager.GetString("Playback_StatusReady", resourceCulture);
            }
        }
        
        public static string Playback_StatusPlaying {
            get {
                return ResourceManager.GetString("Playback_StatusPlaying", resourceCulture);
            }
        }
        
        public static string Playback_StatusComplete {
            get {
                return ResourceManager.GetString("Playback_StatusComplete", resourceCulture);
            }
        }
        
        public static string Playback_StatusStopped {
            get {
                return ResourceManager.GetString("Playback_StatusStopped", resourceCulture);
            }
        }
        
        public static string Playback_StatusPaused {
            get {
                return ResourceManager.GetString("Playback_StatusPaused", resourceCulture);
            }
        }
        
        public static string Playback_StatusError {
            get {
                return ResourceManager.GetString("Playback_StatusError", resourceCulture);
            }
        }
        
        public static string Playback_StatusWaitingNextSequence {
            get {
                return ResourceManager.GetString("Playback_StatusWaitingNextSequence", resourceCulture);
            }
        }
        
        public static string Playback_StatusSequencePlaying {
            get {
                return ResourceManager.GetString("Playback_StatusSequencePlaying", resourceCulture);
            }
        }
        
        public static string Playback_UnnamedMacro {
            get {
                return ResourceManager.GetString("Playback_UnnamedMacro", resourceCulture);
            }
        }
        
        public static string Playback_SequenceCycleInfinite {
            get {
                return ResourceManager.GetString("Playback_SequenceCycleInfinite", resourceCulture);
            }
        }
        
        public static string Playback_SequenceRepeatProgress {
            get {
                return ResourceManager.GetString("Playback_SequenceRepeatProgress", resourceCulture);
            }
        }
        
        public static string Playback_StatusWaitingNextLoop {
            get {
                return ResourceManager.GetString("Playback_StatusWaitingNextLoop", resourceCulture);
            }
        }
        
        public static string Playback_StatusLoopInfinite {
            get {
                return ResourceManager.GetString("Playback_StatusLoopInfinite", resourceCulture);
            }
        }
        
        public static string Playback_StatusLoopProgress {
            get {
                return ResourceManager.GetString("Playback_StatusLoopProgress", resourceCulture);
            }
        }
        
        public static string Playback_StatusStartingIn {
            get {
                return ResourceManager.GetString("Playback_StatusStartingIn", resourceCulture);
            }
        }
        
        public static string Recording_StatusReady {
            get {
                return ResourceManager.GetString("Recording_StatusReady", resourceCulture);
            }
        }
        
        public static string Recording_StatusRecording {
            get {
                return ResourceManager.GetString("Recording_StatusRecording", resourceCulture);
            }
        }
        
        public static string Recording_StatusError {
            get {
                return ResourceManager.GetString("Recording_StatusError", resourceCulture);
            }
        }
        
        public static string Recording_StatusRecordedEvents {
            get {
                return ResourceManager.GetString("Recording_StatusRecordedEvents", resourceCulture);
            }
        }
        
        public static string Recording_StatusLoadedEvents {
            get {
                return ResourceManager.GetString("Recording_StatusLoadedEvents", resourceCulture);
            }
        }
        
        public static string Editor_DefaultMacroName {
            get {
                return ResourceManager.GetString("Editor_DefaultMacroName", resourceCulture);
            }
        }
        
        public static string Editor_StatusReady {
            get {
                return ResourceManager.GetString("Editor_StatusReady", resourceCulture);
            }
        }
        
        public static string Editor_StatusRemovedAction {
            get {
                return ResourceManager.GetString("Editor_StatusRemovedAction", resourceCulture);
            }
        }
        
        public static string Editor_StatusMovedActionUp {
            get {
                return ResourceManager.GetString("Editor_StatusMovedActionUp", resourceCulture);
            }
        }
        
        public static string Editor_StatusMovedActionDown {
            get {
                return ResourceManager.GetString("Editor_StatusMovedActionDown", resourceCulture);
            }
        }
        
        public static string Editor_StatusDuplicatedAction {
            get {
                return ResourceManager.GetString("Editor_StatusDuplicatedAction", resourceCulture);
            }
        }
        
        public static string Editor_StatusClearedAllActions {
            get {
                return ResourceManager.GetString("Editor_StatusClearedAllActions", resourceCulture);
            }
        }
        
        public static string Editor_StatusUndone {
            get {
                return ResourceManager.GetString("Editor_StatusUndone", resourceCulture);
            }
        }
        
        public static string Editor_StatusRedone {
            get {
                return ResourceManager.GetString("Editor_StatusRedone", resourceCulture);
            }
        }
        
        public static string Editor_StatusSelectActionFirst {
            get {
                return ResourceManager.GetString("Editor_StatusSelectActionFirst", resourceCulture);
            }
        }
        
        public static string Editor_StatusCaptureMousePrompt {
            get {
                return ResourceManager.GetString("Editor_StatusCaptureMousePrompt", resourceCulture);
            }
        }
        
        public static string Editor_StatusCaptureKeyPrompt {
            get {
                return ResourceManager.GetString("Editor_StatusCaptureKeyPrompt", resourceCulture);
            }
        }
        
        public static string Editor_StatusCaptureCancelled {
            get {
                return ResourceManager.GetString("Editor_StatusCaptureCancelled", resourceCulture);
            }
        }
        
        public static string Editor_StatusCaptureSelectionChanged {
            get {
                return ResourceManager.GetString("Editor_StatusCaptureSelectionChanged", resourceCulture);
            }
        }
        
        public static string Editor_StatusSaveCancelled {
            get {
                return ResourceManager.GetString("Editor_StatusSaveCancelled", resourceCulture);
            }
        }
        
        public static string Editor_StatusLoadCancelled {
            get {
                return ResourceManager.GetString("Editor_StatusLoadCancelled", resourceCulture);
            }
        }
        
        public static string Editor_StatusLoadFailed {
            get {
                return ResourceManager.GetString("Editor_StatusLoadFailed", resourceCulture);
            }
        }
        
        public static string Editor_StatusInsertedElseBlock {
            get {
                return ResourceManager.GetString("Editor_StatusInsertedElseBlock", resourceCulture);
            }
        }
        
        public static string Editor_StatusElseAlreadyExists {
            get {
                return ResourceManager.GetString("Editor_StatusElseAlreadyExists", resourceCulture);
            }
        }
        
        public static string Editor_StatusSelectIfBlockFirst {
            get {
                return ResourceManager.GetString("Editor_StatusSelectIfBlockFirst", resourceCulture);
            }
        }
        
        public static string Editor_StatusRemovedBlock {
            get {
                return ResourceManager.GetString("Editor_StatusRemovedBlock", resourceCulture);
            }
        }
        
        public static string Editor_StatusOperationBlocked {
            get {
                return ResourceManager.GetString("Editor_StatusOperationBlocked", resourceCulture);
            }
        }
        
        public static string Editor_SaveDialogTitle {
            get {
                return ResourceManager.GetString("Editor_SaveDialogTitle", resourceCulture);
            }
        }
        
        public static string Editor_LoadDialogTitle {
            get {
                return ResourceManager.GetString("Editor_LoadDialogTitle", resourceCulture);
            }
        }
        
        public static string Editor_MacroFileDialogName {
            get {
                return ResourceManager.GetString("Editor_MacroFileDialogName", resourceCulture);
            }
        }
        
        public static string Editor_DialogTitleNoActions {
            get {
                return ResourceManager.GetString("Editor_DialogTitleNoActions", resourceCulture);
            }
        }
        
        public static string Editor_DialogMessageNoActions {
            get {
                return ResourceManager.GetString("Editor_DialogMessageNoActions", resourceCulture);
            }
        }
        
        public static string Editor_DialogTitleValidationErrors {
            get {
                return ResourceManager.GetString("Editor_DialogTitleValidationErrors", resourceCulture);
            }
        }
        
        public static string Editor_ValidationErrorHeader {
            get {
                return ResourceManager.GetString("Editor_ValidationErrorHeader", resourceCulture);
            }
        }
        
        public static string Editor_StatusCapturedPosition {
            get {
                return ResourceManager.GetString("Editor_StatusCapturedPosition", resourceCulture);
            }
        }
        
        public static string Editor_StatusCaptureError {
            get {
                return ResourceManager.GetString("Editor_StatusCaptureError", resourceCulture);
            }
        }
        
        public static string Editor_StatusCapturedKey {
            get {
                return ResourceManager.GetString("Editor_StatusCapturedKey", resourceCulture);
            }
        }
        
        public static string Editor_StatusValidationFailed {
            get {
                return ResourceManager.GetString("Editor_StatusValidationFailed", resourceCulture);
            }
        }
        
        public static string Editor_StatusSaved {
            get {
                return ResourceManager.GetString("Editor_StatusSaved", resourceCulture);
            }
        }
        
        public static string Editor_StatusSaveError {
            get {
                return ResourceManager.GetString("Editor_StatusSaveError", resourceCulture);
            }
        }
        
        public static string Editor_StatusLoaded {
            get {
                return ResourceManager.GetString("Editor_StatusLoaded", resourceCulture);
            }
        }
        
        public static string Editor_StatusLoadedWithWarnings {
            get {
                return ResourceManager.GetString("Editor_StatusLoadedWithWarnings", resourceCulture);
            }
        }
        
        public static string Editor_StatusLoadError {
            get {
                return ResourceManager.GetString("Editor_StatusLoadError", resourceCulture);
            }
        }
        
        public static string Editor_StatusRestoreWarningFallback {
            get {
                return ResourceManager.GetString("Editor_StatusRestoreWarningFallback", resourceCulture);
            }
        }
        
        public static string Editor_StatusAutoManagedAction {
            get {
                return ResourceManager.GetString("Editor_StatusAutoManagedAction", resourceCulture);
            }
        }
        
        public static string Editor_Actions {
            get {
                return ResourceManager.GetString("Editor_Actions", resourceCulture);
            }
        }
        
        public static string Editor_RemoveActionTooltip {
            get {
                return ResourceManager.GetString("Editor_RemoveActionTooltip", resourceCulture);
            }
        }
        
        public static string Editor_Remove {
            get {
                return ResourceManager.GetString("Editor_Remove", resourceCulture);
            }
        }
        
        public static string Editor_RemoveBlockTooltip {
            get {
                return ResourceManager.GetString("Editor_RemoveBlockTooltip", resourceCulture);
            }
        }
        
        public static string Editor_Block {
            get {
                return ResourceManager.GetString("Editor_Block", resourceCulture);
            }
        }
        
        public static string Editor_HideMouseMoves {
            get {
                return ResourceManager.GetString("Editor_HideMouseMoves", resourceCulture);
            }
        }
        
        public static string Editor_HideMouseMovesTooltip {
            get {
                return ResourceManager.GetString("Editor_HideMouseMovesTooltip", resourceCulture);
            }
        }
        
        public static string Editor_HiddenEventsHint {
            get {
                return ResourceManager.GetString("Editor_HiddenEventsHint", resourceCulture);
            }
        }
        
        public static string Editor_HideShortWaits {
            get {
                return ResourceManager.GetString("Editor_HideShortWaits", resourceCulture);
            }
        }
        
        public static string Editor_HideShortWaitsTooltip {
            get {
                return ResourceManager.GetString("Editor_HideShortWaitsTooltip", resourceCulture);
            }
        }
        
        public static string Editor_SimplifyMovement {
            get {
                return ResourceManager.GetString("Editor_SimplifyMovement", resourceCulture);
            }
        }
        
        public static string Editor_SimplifyMovementTooltip {
            get {
                return ResourceManager.GetString("Editor_SimplifyMovementTooltip", resourceCulture);
            }
        }
        
        public static string Editor_MoveUpTooltip {
            get {
                return ResourceManager.GetString("Editor_MoveUpTooltip", resourceCulture);
            }
        }
        
        public static string Editor_MoveDownTooltip {
            get {
                return ResourceManager.GetString("Editor_MoveDownTooltip", resourceCulture);
            }
        }
        
        public static string Editor_DuplicateTooltip {
            get {
                return ResourceManager.GetString("Editor_DuplicateTooltip", resourceCulture);
            }
        }
        
        public static string Editor_AddNewAction {
            get {
                return ResourceManager.GetString("Editor_AddNewAction", resourceCulture);
            }
        }
        
        public static string Editor_AddAction {
            get {
                return ResourceManager.GetString("Editor_AddAction", resourceCulture);
            }
        }
        
        public static string Editor_SelectedActionProperties {
            get {
                return ResourceManager.GetString("Editor_SelectedActionProperties", resourceCulture);
            }
        }
        
        public static string Editor_Type {
            get {
                return ResourceManager.GetString("Editor_Type", resourceCulture);
            }
        }
        
        public static string Editor_InsertElseBlock {
            get {
                return ResourceManager.GetString("Editor_InsertElseBlock", resourceCulture);
            }
        }
        
        public static string Editor_CurrentPositionHint {
            get {
                return ResourceManager.GetString("Editor_CurrentPositionHint", resourceCulture);
            }
        }
        
        public static string Editor_Coordinates {
            get {
                return ResourceManager.GetString("Editor_Coordinates", resourceCulture);
            }
        }
        
        public static string Editor_CapturePosition {
            get {
                return ResourceManager.GetString("Editor_CapturePosition", resourceCulture);
            }
        }
        
        public static string Editor_CancelCapture {
            get {
                return ResourceManager.GetString("Editor_CancelCapture", resourceCulture);
            }
        }
        
        public static string Editor_CoordinateMode {
            get {
                return ResourceManager.GetString("Editor_CoordinateMode", resourceCulture);
            }
        }
        
        public static string Editor_Absolute {
            get {
                return ResourceManager.GetString("Editor_Absolute", resourceCulture);
            }
        }
        
        public static string Editor_Relative {
            get {
                return ResourceManager.GetString("Editor_Relative", resourceCulture);
            }
        }
        
        public static string Editor_MouseButton {
            get {
                return ResourceManager.GetString("Editor_MouseButton", resourceCulture);
            }
        }
        
        public static string Editor_Key {
            get {
                return ResourceManager.GetString("Editor_Key", resourceCulture);
            }
        }
        
        public static string Editor_KeyPlaceholder {
            get {
                return ResourceManager.GetString("Editor_KeyPlaceholder", resourceCulture);
            }
        }
        
        public static string Editor_KeyFallback {
            get {
                return ResourceManager.GetString("Editor_KeyFallback", resourceCulture);
            }
        }
        
        public static string Editor_CaptureKey {
            get {
                return ResourceManager.GetString("Editor_CaptureKey", resourceCulture);
            }
        }
        
        public static string Editor_RandomizeDelay {
            get {
                return ResourceManager.GetString("Editor_RandomizeDelay", resourceCulture);
            }
        }
        
        public static string Editor_DelayMs {
            get {
                return ResourceManager.GetString("Editor_DelayMs", resourceCulture);
            }
        }
        
        public static string Editor_DelayPlaceholder {
            get {
                return ResourceManager.GetString("Editor_DelayPlaceholder", resourceCulture);
            }
        }
        
        public static string Editor_RandomDelayRangeMs {
            get {
                return ResourceManager.GetString("Editor_RandomDelayRangeMs", resourceCulture);
            }
        }
        
        public static string Editor_Min {
            get {
                return ResourceManager.GetString("Editor_Min", resourceCulture);
            }
        }
        
        public static string Editor_Max {
            get {
                return ResourceManager.GetString("Editor_Max", resourceCulture);
            }
        }
        
        public static string Editor_ScrollAmount {
            get {
                return ResourceManager.GetString("Editor_ScrollAmount", resourceCulture);
            }
        }
        
        public static string Editor_Amount {
            get {
                return ResourceManager.GetString("Editor_Amount", resourceCulture);
            }
        }
        
        public static string Editor_ScrollHint {
            get {
                return ResourceManager.GetString("Editor_ScrollHint", resourceCulture);
            }
        }
        
        public static string Editor_SetVariable {
            get {
                return ResourceManager.GetString("Editor_SetVariable", resourceCulture);
            }
        }
        
        public static string Editor_VariableNamePlaceholder {
            get {
                return ResourceManager.GetString("Editor_VariableNamePlaceholder", resourceCulture);
            }
        }
        
        public static string Editor_Value {
            get {
                return ResourceManager.GetString("Editor_Value", resourceCulture);
            }
        }
        
        public static string Editor_SetVariableHint {
            get {
                return ResourceManager.GetString("Editor_SetVariableHint", resourceCulture);
            }
        }
        
        public static string Editor_VariableUpdate {
            get {
                return ResourceManager.GetString("Editor_VariableUpdate", resourceCulture);
            }
        }
        
        public static string Editor_AmountOrVariable {
            get {
                return ResourceManager.GetString("Editor_AmountOrVariable", resourceCulture);
            }
        }
        
        public static string Editor_IncrementDecrementHint {
            get {
                return ResourceManager.GetString("Editor_IncrementDecrementHint", resourceCulture);
            }
        }
        
        public static string Editor_RepeatBlock {
            get {
                return ResourceManager.GetString("Editor_RepeatBlock", resourceCulture);
            }
        }
        
        public static string Editor_CountOrVariable {
            get {
                return ResourceManager.GetString("Editor_CountOrVariable", resourceCulture);
            }
        }
        
        public static string Editor_Condition {
            get {
                return ResourceManager.GetString("Editor_Condition", resourceCulture);
            }
        }
        
        public static string Editor_LeftOperand {
            get {
                return ResourceManager.GetString("Editor_LeftOperand", resourceCulture);
            }
        }
        
        public static string Editor_LeftValue {
            get {
                return ResourceManager.GetString("Editor_LeftValue", resourceCulture);
            }
        }
        
        public static string Editor_RightOperand {
            get {
                return ResourceManager.GetString("Editor_RightOperand", resourceCulture);
            }
        }
        
        public static string Editor_RightValue {
            get {
                return ResourceManager.GetString("Editor_RightValue", resourceCulture);
            }
        }
        
        public static string Editor_ForBlock {
            get {
                return ResourceManager.GetString("Editor_ForBlock", resourceCulture);
            }
        }
        
        public static string Editor_LoopVariablePlaceholder {
            get {
                return ResourceManager.GetString("Editor_LoopVariablePlaceholder", resourceCulture);
            }
        }
        
        public static string Editor_Start {
            get {
                return ResourceManager.GetString("Editor_Start", resourceCulture);
            }
        }
        
        public static string Editor_End {
            get {
                return ResourceManager.GetString("Editor_End", resourceCulture);
            }
        }
        
        public static string Editor_UseExplicitStep {
            get {
                return ResourceManager.GetString("Editor_UseExplicitStep", resourceCulture);
            }
        }
        
        public static string Editor_Step {
            get {
                return ResourceManager.GetString("Editor_Step", resourceCulture);
            }
        }
        
        public static string Editor_SelectActionPrompt {
            get {
                return ResourceManager.GetString("Editor_SelectActionPrompt", resourceCulture);
            }
        }
        
        public static string Editor_RestoreWarnings {
            get {
                return ResourceManager.GetString("Editor_RestoreWarnings", resourceCulture);
            }
        }
        
        public static string Editor_UndoTooltip {
            get {
                return ResourceManager.GetString("Editor_UndoTooltip", resourceCulture);
            }
        }
        
        public static string Editor_Undo {
            get {
                return ResourceManager.GetString("Editor_Undo", resourceCulture);
            }
        }
        
        public static string Editor_RedoTooltip {
            get {
                return ResourceManager.GetString("Editor_RedoTooltip", resourceCulture);
            }
        }
        
        public static string Editor_Redo {
            get {
                return ResourceManager.GetString("Editor_Redo", resourceCulture);
            }
        }
        
        public static string Editor_ClearAllTooltip {
            get {
                return ResourceManager.GetString("Editor_ClearAllTooltip", resourceCulture);
            }
        }
        
        public static string Editor_Clear {
            get {
                return ResourceManager.GetString("Editor_Clear", resourceCulture);
            }
        }
        
        public static string Editor_Load {
            get {
                return ResourceManager.GetString("Editor_Load", resourceCulture);
            }
        }
        
        public static string Editor_Save {
            get {
                return ResourceManager.GetString("Editor_Save", resourceCulture);
            }
        }
        
        public static string TextExpansion_ModeDirectTyping {
            get {
                return ResourceManager.GetString("TextExpansion_ModeDirectTyping", resourceCulture);
            }
        }
        
        public static string TextExpansion_ModePaste {
            get {
                return ResourceManager.GetString("TextExpansion_ModePaste", resourceCulture);
            }
        }
        
        public static string HotkeyCapture_PressAKey {
            get {
                return ResourceManager.GetString("HotkeyCapture_PressAKey", resourceCulture);
            }
        }
        
        public static string HotkeyCapture_ClickToSet {
            get {
                return ResourceManager.GetString("HotkeyCapture_ClickToSet", resourceCulture);
            }
        }
        
        public static string HotkeyCapture_ServiceError {
            get {
                return ResourceManager.GetString("HotkeyCapture_ServiceError", resourceCulture);
            }
        }
        
        public static string Dialog_Yes {
            get {
                return ResourceManager.GetString("Dialog_Yes", resourceCulture);
            }
        }
        
        public static string Dialog_No {
            get {
                return ResourceManager.GetString("Dialog_No", resourceCulture);
            }
        }
        
        public static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog_Ok", resourceCulture);
            }
        }
        
        public static string Tray_ShowHide {
            get {
                return ResourceManager.GetString("Tray_ShowHide", resourceCulture);
            }
        }
        
        public static string Tray_StartRecording {
            get {
                return ResourceManager.GetString("Tray_StartRecording", resourceCulture);
            }
        }
        
        public static string Tray_StartPlayback {
            get {
                return ResourceManager.GetString("Tray_StartPlayback", resourceCulture);
            }
        }
        
        public static string Tray_Stop {
            get {
                return ResourceManager.GetString("Tray_Stop", resourceCulture);
            }
        }
        
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        public static string Editor_CurrentPositionClick {
            get {
                return ResourceManager.GetString("Editor_CurrentPositionClick", resourceCulture);
            }
        }
        
        public static string Editor_CurrentPositionHold {
            get {
                return ResourceManager.GetString("Editor_CurrentPositionHold", resourceCulture);
            }
        }
        
        public static string Editor_CurrentPositionRelease {
            get {
                return ResourceManager.GetString("Editor_CurrentPositionRelease", resourceCulture);
            }
        }
        
        public static string Editor_CurrentPositionUse {
            get {
                return ResourceManager.GetString("Editor_CurrentPositionUse", resourceCulture);
            }
        }
        
        public static string Editor_RawScriptStep {
            get {
                return ResourceManager.GetString("Editor_RawScriptStep", resourceCulture);
            }
        }
        
        public static string Editor_TextToType {
            get {
                return ResourceManager.GetString("Editor_TextToType", resourceCulture);
            }
        }
        
        public static string Editor_OriginalScriptLine {
            get {
                return ResourceManager.GetString("Editor_OriginalScriptLine", resourceCulture);
            }
        }
        
        public static string Editor_EnterTextToType {
            get {
                return ResourceManager.GetString("Editor_EnterTextToType", resourceCulture);
            }
        }
        
        public static string Editor_RawScriptHint {
            get {
                return ResourceManager.GetString("Editor_RawScriptHint", resourceCulture);
            }
        }
        
        public static string Editor_TextToTypeHint {
            get {
                return ResourceManager.GetString("Editor_TextToTypeHint", resourceCulture);
            }
        }
        
        public static string Editor_StatusAddedAction {
            get {
                return ResourceManager.GetString("Editor_StatusAddedAction", resourceCulture);
            }
        }
        
        public static string Editor_BlockName_If {
            get {
                return ResourceManager.GetString("Editor_BlockName_If", resourceCulture);
            }
        }
        
        public static string Editor_BlockName_Else {
            get {
                return ResourceManager.GetString("Editor_BlockName_Else", resourceCulture);
            }
        }
        
        public static string Editor_BlockName_While {
            get {
                return ResourceManager.GetString("Editor_BlockName_While", resourceCulture);
            }
        }
        
        public static string Editor_BlockName_For {
            get {
                return ResourceManager.GetString("Editor_BlockName_For", resourceCulture);
            }
        }
        
        public static string Editor_BlockName_Repeat {
            get {
                return ResourceManager.GetString("Editor_BlockName_Repeat", resourceCulture);
            }
        }
        
        public static string Editor_BlockName_Block {
            get {
                return ResourceManager.GetString("Editor_BlockName_Block", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseMoveAbsolute {
            get {
                return ResourceManager.GetString("Editor_Action_MouseMoveAbsolute", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseMoveRelative {
            get {
                return ResourceManager.GetString("Editor_Action_MouseMoveRelative", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseClickCurrent {
            get {
                return ResourceManager.GetString("Editor_Action_MouseClickCurrent", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseClick {
            get {
                return ResourceManager.GetString("Editor_Action_MouseClick", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseClickAbsolute {
            get {
                return ResourceManager.GetString("Editor_Action_MouseClickAbsolute", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseClickRelative {
            get {
                return ResourceManager.GetString("Editor_Action_MouseClickRelative", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseDown {
            get {
                return ResourceManager.GetString("Editor_Action_MouseDown", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseDownCurrent {
            get {
                return ResourceManager.GetString("Editor_Action_MouseDownCurrent", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseDownAbsolute {
            get {
                return ResourceManager.GetString("Editor_Action_MouseDownAbsolute", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseDownRelative {
            get {
                return ResourceManager.GetString("Editor_Action_MouseDownRelative", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseUp {
            get {
                return ResourceManager.GetString("Editor_Action_MouseUp", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseUpCurrent {
            get {
                return ResourceManager.GetString("Editor_Action_MouseUpCurrent", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseUpAbsolute {
            get {
                return ResourceManager.GetString("Editor_Action_MouseUpAbsolute", resourceCulture);
            }
        }
        
        public static string Editor_Action_MouseUpRelative {
            get {
                return ResourceManager.GetString("Editor_Action_MouseUpRelative", resourceCulture);
            }
        }
        
        public static string Editor_Action_KeyPress {
            get {
                return ResourceManager.GetString("Editor_Action_KeyPress", resourceCulture);
            }
        }
        
        public static string Editor_Action_KeyDown {
            get {
                return ResourceManager.GetString("Editor_Action_KeyDown", resourceCulture);
            }
        }
        
        public static string Editor_Action_KeyUp {
            get {
                return ResourceManager.GetString("Editor_Action_KeyUp", resourceCulture);
            }
        }
        
        public static string Editor_Action_DelayRandom {
            get {
                return ResourceManager.GetString("Editor_Action_DelayRandom", resourceCulture);
            }
        }
        
        public static string Editor_Action_Delay {
            get {
                return ResourceManager.GetString("Editor_Action_Delay", resourceCulture);
            }
        }
        
        public static string Editor_Action_ScrollUp {
            get {
                return ResourceManager.GetString("Editor_Action_ScrollUp", resourceCulture);
            }
        }
        
        public static string Editor_Action_ScrollDown {
            get {
                return ResourceManager.GetString("Editor_Action_ScrollDown", resourceCulture);
            }
        }
        
        public static string Editor_Action_ScrollRight {
            get {
                return ResourceManager.GetString("Editor_Action_ScrollRight", resourceCulture);
            }
        }
        
        public static string Editor_Action_ScrollLeft {
            get {
                return ResourceManager.GetString("Editor_Action_ScrollLeft", resourceCulture);
            }
        }
        
        public static string Editor_Action_TextInputEmpty {
            get {
                return ResourceManager.GetString("Editor_Action_TextInputEmpty", resourceCulture);
            }
        }
        
        public static string Editor_Action_TextInput {
            get {
                return ResourceManager.GetString("Editor_Action_TextInput", resourceCulture);
            }
        }
        
        public static string Editor_Action_SetVariableShort {
            get {
                return ResourceManager.GetString("Editor_Action_SetVariableShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_IncrementVariableShort {
            get {
                return ResourceManager.GetString("Editor_Action_IncrementVariableShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_DecrementVariableShort {
            get {
                return ResourceManager.GetString("Editor_Action_DecrementVariableShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_RepeatBlockShort {
            get {
                return ResourceManager.GetString("Editor_Action_RepeatBlockShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_IfBlockShort {
            get {
                return ResourceManager.GetString("Editor_Action_IfBlockShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_ElseBlockShort {
            get {
                return ResourceManager.GetString("Editor_Action_ElseBlockShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_WhileBlockShort {
            get {
                return ResourceManager.GetString("Editor_Action_WhileBlockShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_ForBlockShort {
            get {
                return ResourceManager.GetString("Editor_Action_ForBlockShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_BreakShort {
            get {
                return ResourceManager.GetString("Editor_Action_BreakShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_ContinueShort {
            get {
                return ResourceManager.GetString("Editor_Action_ContinueShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_EndBlockShort {
            get {
                return ResourceManager.GetString("Editor_Action_EndBlockShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_RawScriptStepShort {
            get {
                return ResourceManager.GetString("Editor_Action_RawScriptStepShort", resourceCulture);
            }
        }
        
        public static string Editor_Action_RawScriptStep {
            get {
                return ResourceManager.GetString("Editor_Action_RawScriptStep", resourceCulture);
            }
        }
        
        public static string Editor_Action_UnknownShort {
            get {
                return ResourceManager.GetString("Editor_Action_UnknownShort", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_MouseMove {
            get {
                return ResourceManager.GetString("Editor_ActionType_MouseMove", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_MouseClick {
            get {
                return ResourceManager.GetString("Editor_ActionType_MouseClick", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_MouseDown {
            get {
                return ResourceManager.GetString("Editor_ActionType_MouseDown", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_MouseUp {
            get {
                return ResourceManager.GetString("Editor_ActionType_MouseUp", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_KeyPress {
            get {
                return ResourceManager.GetString("Editor_ActionType_KeyPress", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_KeyDown {
            get {
                return ResourceManager.GetString("Editor_ActionType_KeyDown", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_KeyUp {
            get {
                return ResourceManager.GetString("Editor_ActionType_KeyUp", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_Delay {
            get {
                return ResourceManager.GetString("Editor_ActionType_Delay", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_ScrollVertical {
            get {
                return ResourceManager.GetString("Editor_ActionType_ScrollVertical", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_ScrollHorizontal {
            get {
                return ResourceManager.GetString("Editor_ActionType_ScrollHorizontal", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_TextInput {
            get {
                return ResourceManager.GetString("Editor_ActionType_TextInput", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_SetVariable {
            get {
                return ResourceManager.GetString("Editor_ActionType_SetVariable", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_IncrementVariable {
            get {
                return ResourceManager.GetString("Editor_ActionType_IncrementVariable", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_DecrementVariable {
            get {
                return ResourceManager.GetString("Editor_ActionType_DecrementVariable", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_RepeatBlockStart {
            get {
                return ResourceManager.GetString("Editor_ActionType_RepeatBlockStart", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_IfBlockStart {
            get {
                return ResourceManager.GetString("Editor_ActionType_IfBlockStart", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_ElseBlockStart {
            get {
                return ResourceManager.GetString("Editor_ActionType_ElseBlockStart", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_WhileBlockStart {
            get {
                return ResourceManager.GetString("Editor_ActionType_WhileBlockStart", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_ForBlockStart {
            get {
                return ResourceManager.GetString("Editor_ActionType_ForBlockStart", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_BlockEnd {
            get {
                return ResourceManager.GetString("Editor_ActionType_BlockEnd", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_Break {
            get {
                return ResourceManager.GetString("Editor_ActionType_Break", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_Continue {
            get {
                return ResourceManager.GetString("Editor_ActionType_Continue", resourceCulture);
            }
        }
        
        public static string Editor_ActionType_RawScriptStep {
            get {
                return ResourceManager.GetString("Editor_ActionType_RawScriptStep", resourceCulture);
            }
        }
        
        public static string MouseButton_Left {
            get {
                return ResourceManager.GetString("MouseButton_Left", resourceCulture);
            }
        }
        
        public static string MouseButton_Right {
            get {
                return ResourceManager.GetString("MouseButton_Right", resourceCulture);
            }
        }
        
        public static string MouseButton_Middle {
            get {
                return ResourceManager.GetString("MouseButton_Middle", resourceCulture);
            }
        }
        
        public static string MouseButton_ScrollUp {
            get {
                return ResourceManager.GetString("MouseButton_ScrollUp", resourceCulture);
            }
        }
        
        public static string MouseButton_ScrollDown {
            get {
                return ResourceManager.GetString("MouseButton_ScrollDown", resourceCulture);
            }
        }
        
        public static string MouseButton_ScrollLeft {
            get {
                return ResourceManager.GetString("MouseButton_ScrollLeft", resourceCulture);
            }
        }
        
        public static string MouseButton_ScrollRight {
            get {
                return ResourceManager.GetString("MouseButton_ScrollRight", resourceCulture);
            }
        }
        
        public static string Language_Chinese {
            get {
                return ResourceManager.GetString("Language_Chinese", resourceCulture);
            }
        }
        
        public static string Language_Japanese {
            get {
                return ResourceManager.GetString("Language_Japanese", resourceCulture);
            }
        }
        
        public static string Language_Spanish {
            get {
                return ResourceManager.GetString("Language_Spanish", resourceCulture);
            }
        }
        
        public static string Language_Arabic {
            get {
                return ResourceManager.GetString("Language_Arabic", resourceCulture);
            }
        }
        
        public static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        public static string Language_Portuguese {
            get {
                return ResourceManager.GetString("Language_Portuguese", resourceCulture);
            }
        }
        
        public static string Language_Russian {
            get {
                return ResourceManager.GetString("Language_Russian", resourceCulture);
            }
        }
        
        public static string Editor_StatusRemovedSelectedActions {
            get {
                return ResourceManager.GetString("Editor_StatusRemovedSelectedActions", resourceCulture);
            }
        }
        
        public static string Editor_StatusDuplicatedSelectedActions {
            get {
                return ResourceManager.GetString("Editor_StatusDuplicatedSelectedActions", resourceCulture);
            }
        }
        
        public static string Editor_StatusMovedSelectedActionsUp {
            get {
                return ResourceManager.GetString("Editor_StatusMovedSelectedActionsUp", resourceCulture);
            }
        }
        
        public static string Editor_StatusMovedSelectedActionsDown {
            get {
                return ResourceManager.GetString("Editor_StatusMovedSelectedActionsDown", resourceCulture);
            }
        }
        
        public static string Editor_RemoveSelectedActionsTooltip {
            get {
                return ResourceManager.GetString("Editor_RemoveSelectedActionsTooltip", resourceCulture);
            }
        }
        
        public static string Editor_RemoveSelected {
            get {
                return ResourceManager.GetString("Editor_RemoveSelected", resourceCulture);
            }
        }
        
        public static string Editor_SimplifiedMovementHint {
            get {
                return ResourceManager.GetString("Editor_SimplifiedMovementHint", resourceCulture);
            }
        }
        
        public static string Editor_DeleteHiddenEvents {
            get {
                return ResourceManager.GetString("Editor_DeleteHiddenEvents", resourceCulture);
            }
        }
        
        public static string Editor_DeleteHiddenEventsTooltip {
            get {
                return ResourceManager.GetString("Editor_DeleteHiddenEventsTooltip", resourceCulture);
            }
        }
        
        public static string Editor_StatusDeletedHiddenEvents {
            get {
                return ResourceManager.GetString("Editor_StatusDeletedHiddenEvents", resourceCulture);
            }
        }
        
        public static string Editor_StatusNoHiddenEventsToDelete {
            get {
                return ResourceManager.GetString("Editor_StatusNoHiddenEventsToDelete", resourceCulture);
            }
        }
        
        public static string Editor_SelectedActionsFormat {
            get {
                return ResourceManager.GetString("Editor_SelectedActionsFormat", resourceCulture);
            }
        }
    }
}
