#!/usr/bin/env bash
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Find project root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "CrossMacro - NuGet Dependencies Update Script"
echo "=============================================="
echo ""

# Navigate to root directory
cd "$PROJECT_ROOT"

# Check required tools
echo -e "${BLUE}Checking required tools...${NC}"
MISSING_TOOLS=0

if ! command -v jq &> /dev/null; then
    echo -e "${RED}Error: 'jq' is not installed.${NC}"
    echo "  Install: nix-shell -p jq"
    MISSING_TOOLS=1
fi

if ! command -v nix-prefetch-url &> /dev/null; then
    echo -e "${RED}Error: 'nix-prefetch-url' not found. Is Nix installed?${NC}"
    MISSING_TOOLS=1
fi

if ! command -v nix-hash &> /dev/null; then
    echo -e "${RED}Error: 'nix-hash' not found. Is Nix installed?${NC}"
    MISSING_TOOLS=1
fi

if ! command -v dotnet &> /dev/null; then
    echo -e "${RED}Error: 'dotnet' is not installed.${NC}"
    MISSING_TOOLS=1
fi

if [ $MISSING_TOOLS -eq 1 ]; then
    exit 1
fi

echo -e "${GREEN}✓ All tools found${NC}"
echo ""

# Restore project (to generate project.assets.json)
echo -e "${BLUE}Restoring project...${NC}"
dotnet restore src/CrossMacro.UI/CrossMacro.UI.csproj

# Find the specific project.assets.json
ASSETS_FILE="src/CrossMacro.UI/obj/project.assets.json"
if [ ! -f "$ASSETS_FILE" ]; then
    echo -e "${RED}Error: $ASSETS_FILE not found after restore${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Found: $ASSETS_FILE${NC}"
echo ""

# Generate deps.nix
echo -e "${BLUE}Generating deps.nix...${NC}"

# Create temporary file for atomic write
TEMP_DEPS=$(mktemp)
trap "rm -f $TEMP_DEPS" EXIT

echo "# Auto-generated by update-nix-deps.sh" > "$TEMP_DEPS"
echo "{ fetchNuGet }: [" >> "$TEMP_DEPS"

# Extract packages
mapfile -t PACKAGES < <(jq -r '
  .libraries
  | to_entries[]
  | select(.value.type == "package")
  | "\(.key)"
' "$ASSETS_FILE" | sort -u)

TOTAL=${#PACKAGES[@]}
CURRENT=0
FAILED=0

echo "Found $TOTAL NuGet packages to process"
echo ""

# Process each package
for package in "${PACKAGES[@]}"; do
    CURRENT=$((CURRENT + 1))

    # Split package name and version
    IFS='/' read -r name version <<< "$package"

    # Skip if version is empty
    if [ -z "$version" ]; then
        echo -e "${YELLOW}[$CURRENT/$TOTAL] Skipping: $name (no version)${NC}"
        continue
    fi

    echo -n "[$CURRENT/$TOTAL] Fetching: $name/$version ... "

    # Try lowercase name first (standard NuGet behavior)
    name_lower=$(echo "$name" | tr '[:upper:]' '[:lower:]')
    url="https://api.nuget.org/v3-flatcontainer/${name_lower}/${version}/${name_lower}.${version}.nupkg"

    # Fetch hash and convert to SRI format
    if hash=$(nix-prefetch-url --type sha256 "$url" 2>/dev/null); then
        # Convert base32 hash to SRI format (sha256-base64)
        sri_hash=$(nix-hash --type sha256 --to-sri "$hash")

        echo -e "${GREEN}✓${NC}"
        echo "  (fetchNuGet { pname = \"${name}\"; version = \"${version}\"; hash = \"${sri_hash}\"; })" >> "$TEMP_DEPS"
    else
        echo -e "${RED}✗${NC}"
        FAILED=$((FAILED + 1))

        # Try alternative URL with original casing
        echo -n "    Retrying with original casing ... "
        url_alt="https://api.nuget.org/v3-flatcontainer/${name}/${version}/${name}.${version}.nupkg"

        if hash=$(nix-prefetch-url --type sha256 "$url_alt" 2>/dev/null); then
            sri_hash=$(nix-hash --type sha256 --to-sri "$hash")
            echo -e "${GREEN}✓${NC}"
            echo "  (fetchNuGet { pname = \"${name}\"; version = \"${version}\"; hash = \"${sri_hash}\"; })" >> "$TEMP_DEPS"
            FAILED=$((FAILED - 1))
        else
            echo -e "${RED}✗ FAILED${NC}"
            echo -e "${YELLOW}    Warning: Could not fetch $name/$version${NC}"
            echo "  # FAILED: $name/$version - could not fetch" >> "$TEMP_DEPS"
        fi
    fi
done

echo "]" >> "$TEMP_DEPS"

# Move temp file to final location only if successful
mv "$TEMP_DEPS" deps.nix

echo ""
if [ $FAILED -eq 0 ]; then
    echo -e "${GREEN}✓ deps.nix successfully generated! ($CURRENT packages)${NC}"
else
    echo -e "${YELLOW}⚠ deps.nix generated with $FAILED failures out of $CURRENT packages${NC}"
fi

# Validate deps.nix
echo ""
echo -e "${BLUE}Validating deps.nix...${NC}"

# First check: Parse syntax
if ! nix-instantiate --parse deps.nix > /dev/null 2>&1; then
    echo -e "${RED}✗ deps.nix has syntax errors${NC}"
    echo ""
    echo "Parse error details:"
    nix-instantiate --parse deps.nix 2>&1 | head -20
    exit 1
fi

echo -e "${GREEN}✓ Syntax is valid${NC}"

# Second check: Evaluate expression
if ! nix-instantiate --eval --strict --expr 'let pkgs = import <nixpkgs> {}; in builtins.length (import ./deps.nix { inherit (pkgs) fetchNuGet; })' > /dev/null 2>&1; then
    echo -e "${YELLOW}⚠ Warning: Could not fully evaluate deps.nix (this may be OK)${NC}"
else
    PKG_COUNT=$(nix-instantiate --eval --strict --expr 'let pkgs = import <nixpkgs> {}; in builtins.length (import ./deps.nix { inherit (pkgs) fetchNuGet; })' 2>/dev/null || echo "?")
    echo -e "${GREEN}✓ Expression evaluates correctly ($PKG_COUNT packages)${NC}"
fi

# Show summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Summary:"
echo "  Total packages: $CURRENT"
echo "  Failed: $FAILED"
echo "  Output: deps.nix ($(wc -l < deps.nix) lines)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}✓ Done! You can now run:${NC}"
echo "  nix build -L"
echo ""
