#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Find project root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "CrossMacro - NuGet Dependencies Update Script"
echo "=============================================="
echo ""

# Navigate to root directory
cd "$PROJECT_ROOT"

# 1. Check required tools
if ! command -v jq &> /dev/null; then
    echo -e "${RED}Error: 'jq' is not installed. Please install it.${NC}"
    exit 1
fi

if ! command -v nix-prefetch-url &> /dev/null; then
    echo -e "${RED}Error: 'nix-prefetch-url' not found. Is Nix installed?${NC}"
    exit 1
fi

if ! command -v dotnet &> /dev/null; then
    echo -e "${RED}Error: 'dotnet' is not installed.${NC}"
    exit 1
fi

# 2. Restore project (to generate project.assets.json)
echo "Restoring project..."
dotnet restore

# 3. Generate deps.nix
echo "Generating deps.nix..."
echo "# Auto-generated by update-deps.sh" > deps.nix
echo "{ fetchNuGet }: [" >> deps.nix

# Read packages from project.assets.json and get their hashes
find . -name "project.assets.json" -type f | while read -r assets_file; do
    jq -r '.libraries | to_entries[] | select(.value.type == "package") | "\(.key)"' "$assets_file" | sort -u
done | sort -u | while read -r package; do
    name=$(echo "$package" | cut -d'/' -f1)
    version=$(echo "$package" | cut -d'/' -f2)
    
    # Calculate hash
    url="https://api.nuget.org/v3-flatcontainer/${name,,}/$version/${name,,}.$version.nupkg"
    echo "  Fetching: $name/$version"
    
    hash=$(nix-prefetch-url "$url" 2>/dev/null || echo "")
    
    if [ -n "$hash" ]; then
        cat >> deps.nix << EOF
  (fetchNuGet { pname = "$name"; version = "$version"; hash = "sha256-$hash"; })
EOF
    fi
done

echo "]" >> deps.nix

echo -e "${GREEN}deps.nix successfully updated!${NC}"

# 4. Clean up artifact files
echo "Cleaning up..."
find . -type d -name "obj" -exec rm -rf {} + 2>/dev/null || true
find . -type f -name "project.assets.json" -delete 2>/dev/null || true

echo -e "${GREEN}Cleanup completed.${NC}"
