global using Avalonia;
global using CrossMacro.Cli.Services;
global using CrossMacro.Cli;
global using CrossMacro.Core.Services;
global using CrossMacro.Infrastructure.DependencyInjection;
global using CrossMacro.Infrastructure.Logging;
global using CrossMacro.Infrastructure.Services;
global using CrossMacro.Platform.Abstractions;
global using CrossMacro.Platform.Linux.Clipboard;
global using CrossMacro.Platform.Linux.DependencyInjection;
global using CrossMacro.Platform.Linux.Services;
global using CrossMacro.UI.DependencyInjection;
global using CrossMacro.UI.Services;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.DependencyInjection;
global using PlatformFlatpakClipboard = CrossMacro.Platform.Linux.Clipboard.FlatpakHostClipboardService;
global using PlatformFlatpakImageClipboard = CrossMacro.Platform.Linux.Clipboard.FlatpakHostImageClipboardService;
global using PlatformLinuxClipboard = CrossMacro.Platform.Linux.Clipboard.LinuxShellClipboardService;
global using PlatformLinuxImageClipboard = CrossMacro.Platform.Linux.Clipboard.LinuxShellImageClipboardService;
global using PlatformProcessRunner = CrossMacro.Platform.Abstractions.IProcessRunner;
global using Serilog;
global using System.Runtime.CompilerServices;
global using System.Threading.Tasks;
global using System.Threading;
global using System;
