global using CrossMacro.Application.Automation;
global using CrossMacro.Cli;
global using CrossMacro.Cli.Commands;
global using CrossMacro.Cli.DependencyInjection;
global using CrossMacro.Cli.Services;
global using CrossMacro.Core.Models;
global using CrossMacro.Core.Services;
global using CrossMacro.Core.Services.Playback;
global using CrossMacro.Daemon.Contracts.Ipc;
global using CrossMacro.Infrastructure.DependencyInjection;
global using CrossMacro.Infrastructure.Logging;
global using CrossMacro.Infrastructure.Services;
global using CrossMacro.Infrastructure.Services.Playback;
global using CrossMacro.Infrastructure.Services.Recording.Strategies;
global using CrossMacro.Infrastructure.Services.ScreenCapture;
global using CrossMacro.Infrastructure.Services.ScreenReading;
global using CrossMacro.Platform.Abstractions;
global using CrossMacro.Platform.Abstractions.Diagnostics;
global using CrossMacro.TestInfrastructure;
global using FluentAssertions;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using NSubstitute;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using System.Threading;
global using System.Threading.Tasks;
global using Xunit;
global using CoreLogging = CrossMacro.Core.Logging;
global using CrossMacroPlatformWarmupService = CrossMacro.Platform.Abstractions.IScreenReadingWarmupService;
global using CliRunExecutionRequest = CrossMacro.Cli.Services.RunExecutionRequest;
global using ApplicationRuntimeLifecycleStep = CrossMacro.Application.Runtime.RuntimeLifecycleStep;
global using ApplicationRuntimeLifecycle = CrossMacro.Application.Runtime.RuntimeLifecycle;
